### ISSUE TITLE
Awesome work!

### ISSUE THREAD

**Issue by zejtin** [yurkinh/FancyFrame#1]
Just wanted to reach out to you and say this is some awesome work you've done! 🤘

**Comment by yurkinh** [comment]
@zejtin  Thanks. I also have an idea (but have no time :) ) to reimplement it with Xamarin.Forms Shapes or [System.Graphics](https://github.com/jonlipsky/System.Graphics) hence it will still have a single implementation but will support Clipping.

**Comment by zejtin** [comment]
@yurkinh I was not aware of System.Graphics library :) Once more great job man!

**Comment by zejtin** [comment]
I recommended you to Weekly Xamarin - http://weeklyxamarin.com this awesome library will be part of next issue.
Hope you don't mind :)

**Comment by yurkinh** [comment]
Sure)).
Actually, I'm an active reader and subscriber of weeklyxamarin and has been already published once on issue 198).

**Comment by zejtin** [comment]
Hahaha, I totally missed it somehow :/ it doesn't hurt to be published again :) this time it is NuGet of the week 🥇
