### ISSUE TITLE
Bitmap image quality is degraded compared to the source image

### ISSUE THREAD

**Issue by vinnie035** [yurkinh/FancyFrame#2]
I noticed that when you display an image inside a fancyframe, the quality is degraded compared to the original. It shows some sort of aliasing.

You can see in the attached file the difference in quality between a fancyframe (the upper one) and the same image embedded in a standard frame (the lower one).

I tried with skiasharp 1.68.3 and 2.80.0. More recent version of skiasharp crashes on WPF.

![francyframe_quality_annoted](https://user-images.githubusercontent.com/4272956/173052203-ab664fe1-5b8e-485d-894d-c632c5e5d317.png)

**Comment by yurkinh** [comment]
Hi @vinnie035 
Thanks for the feedback.
Image is rendered with Skiasharp and scaling is applied to it. I will take a look  how we can imrove image quality.

**Comment by vinnie035** [comment]
Indeed, the degradation comes from the scaling process. Maybe you could scale the image from the stream, before sending it for rendering to skiasharp.

**Comment by vinnie035** [comment]
I fixed my problem using a new SKPaint :

` canvas.DrawBitmap(bitmap, roundRect.Rect, BitmapStretch.AspectFill, BitmapAlignment.Center, BitmapAlignment.Center, new SKPaint { FilterQuality = SKFilterQuality.High });`

I guess I could even use SKFilterQuality.Low for better performance if necessary...
